name: Publish and deploy Docker image LATEST

on:
  push:
    branches: master
  schedule:
    - cron: '0 0 * * 1'



env:
  IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
  IBM_CLOUD_REGION: eu-de
  ICR_NAMESPACE: lgln-bavi
  REGISTRY_HOSTNAME: de.icr.io
  IMAGE_NAME: vt-styles
  GITHUB_SHA: ${{ github.sha }}
  IKS_CLUSTER: bpb6t7ff0u016hl0n65g
  IKS_NAMESPACE: bavi-dev
  DEPLOYMENT_NAME: vt-styles-deployment

jobs:
  build:
    name: Build and push Docker image to IBM Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        id: prep
        run: echo ::set-output name=sha_short::`echo ${GITHUB_SHA} | cut -c1-7`

      - name: Checkout
        uses: actions/checkout@v3
      # Build the Docker image
      - name: Build with Docker
        run: |
          docker build -t "$REGISTRY_HOSTNAME"/"$ICR_NAMESPACE"/"$IMAGE_NAME":${{ steps.prep.outputs.sha_short }}  \
            --build-arg GITHUB_REF="$GITHUB_REF" .
          docker build -t "$REGISTRY_HOSTNAME"/"$ICR_NAMESPACE"/"$IMAGE_NAME":latest  \
            --build-arg GITHUB_REF="$GITHUB_REF" .
            # Scan with trivy     
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'de.icr.io/lgln-bavi/vt-styles:${{ steps.prep.outputs.sha_short }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'  
      # Download and Install IBM Cloud CLI
      - name: Install IBM Cloud CLI
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud --version
          ibmcloud config --check-version=false
          ibmcloud plugin install container-registry
      # Authenticate with IBM Cloud CLI
      - name: Authenticate with IBM Cloud CLI
        run: |
          ibmcloud login --apikey "${IBM_CLOUD_API_KEY}" -r "${IBM_CLOUD_REGION}" -g LGLN_bavimobil
          ibmcloud cr region-set "${IBM_CLOUD_REGION}"
          ibmcloud cr login

      # Push the image to IBM Container Registry
      - name: Push the image to ICR
        run: |
          docker push $REGISTRY_HOSTNAME/$ICR_NAMESPACE/$IMAGE_NAME:${{ steps.prep.outputs.sha_short }} 
          docker push $REGISTRY_HOSTNAME/$ICR_NAMESPACE/$IMAGE_NAME:nightly   

  deploy:
    name: Deploy Docker image to IKS cluster
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        id: prep
        run: echo ::set-output name=sha_short::`echo ${GITHUB_SHA} | cut -c1-7`

      - name: Install IBM Cloud CLI
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud --version
          ibmcloud config --check-version=false
          ibmcloud plugin install -f kubernetes-service

      - name: Authenticate with IBM Cloud CLI
        run: |
          ibmcloud login --apikey "${IBM_CLOUD_API_KEY}" -r "${IBM_CLOUD_REGION}" -g LGLN_power

      - name: Deploy to IKS dev
        run: |
          ibmcloud ks cluster config --cluster $IKS_CLUSTER
          kubectl config set-context --current --namespace=bavi-dev
          kubectl set image deployment/$DEPLOYMENT_NAME vt-styles=basisvisualisierung/vt-styles:${{ steps.prep.outputs.sha_short }}
          kubectl rollout status deployment/$DEPLOYMENT_NAME    

