name: Publish and deploy Docker image LATEST

on:
  push:
    branches: master
  schedule:
    - cron: '0 0 * * 1'



env:
  IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
  IBM_CLOUD_REGION: eu-de
  IKS_CLUSTER: bpb6t7ff0u016hl0n65g
  DEPLOYMENT_NAME: vt-styles-deployment

jobs:
  build:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        id: prep
        run: echo ::set-output name=sha_short::`echo ${GITHUB_SHA} | cut -c1-7`

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: basisvisualisierung/vt-styles:latest,basisvisualisierung/vt-styles:${{ steps.prep.outputs.sha_short }}      
  scan:
    name: Scan for vulnerabilities
    needs: build    
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        id: prep
        run: echo ::set-output name=sha_short::`echo ${GITHUB_SHA} | cut -c1-7`

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: basisvisualisierung/vt-styles:${{ steps.prep.outputs.sha_short }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH' 
  deploy:
    name: Deploy Docker image to IKS cluster
    needs: scan
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        id: prep
        run: echo ::set-output name=sha_short::`echo ${GITHUB_SHA} | cut -c1-7`

      - name: Install IBM Cloud CLI
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud --version
          ibmcloud config --check-version=false
          ibmcloud plugin install -f kubernetes-service

      - name: Authenticate with IBM Cloud CLI
        run: |
          ibmcloud login --apikey "${IBM_CLOUD_API_KEY}" -r "${IBM_CLOUD_REGION}" -g LGLN_power

      - name: Deploy to IKS dev
        run: |
          ibmcloud ks cluster config --cluster $IKS_CLUSTER
          kubectl config set-context --current --namespace=bavi-dev
          kubectl set image deployment/$DEPLOYMENT_NAME vt-styles=basisvisualisierung/vt-styles:${{ steps.prep.outputs.sha_short }}
          kubectl rollout status deployment/$DEPLOYMENT_NAME    

      - name: Deploy to IKS staging
        run: |
          ibmcloud ks cluster config --cluster $IKS_CLUSTER
          kubectl config set-context --current --namespace=bavi-staging
          kubectl set image deployment/$DEPLOYMENT_NAME vt-styles=basisvisualisierung/vt-styles:${{ steps.prep.outputs.sha_short }}
          kubectl rollout status deployment/$DEPLOYMENT_NAME   
