name: Publish and deploy Docker image RELEASE

on:
  push:
    tags: 
      - 'v*.*.*'

env:
  IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
  IBM_CLOUD_REGION: eu-de
  ICR_NAMESPACE: lgln-bavi
  REGISTRY_HOSTNAME: de.icr.io
  IMAGE_NAME: vt-styles
  GITHUB_SHA: ${{ github.sha }}
  IKS_CLUSTER: bpb6t7ff0u016hl0n65g
  IKS_NAMESPACE: bavi-dev
  DEPLOYMENT_NAME: vt-styles-deployment

jobs:
  build:
    name: Build and push Docker image to IBM Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        id: prep
        run: |
          TAGS=basisvisualisierung/vt-styles:${GITHUB_REF#refs/tags/}
          echo "tags=${TAGS}"  >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v3
      # Build the Docker image
      - name: Build with Docker
        run: |
          docker build -t "$REGISTRY_HOSTNAME"/"$ICR_NAMESPACE"/"$IMAGE_NAME":$${{ steps.prep.outputs.tags }}  \
            --build-arg GITHUB_REF="$GITHUB_REF" .
          docker build -t "$REGISTRY_HOSTNAME"/"$ICR_NAMESPACE"/"$IMAGE_NAME":latest  \
            --build-arg GITHUB_REF="$GITHUB_REF" .
            # Scan with trivy     
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'de.icr.io/lgln-bavi/vt-styles:$${{ steps.prep.outputs.tags }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'  
      # Login to IBM Cloud
      - name: Login to IBM Cloud
        run: docker login "$REGISTRY_HOSTNAME" -u iamapikey -p "$IBM_CLOUD_API_KEY"

      # Push the image to IBM Container Registry
      - name: Push the image to ICR
        run: |
          docker push $REGISTRY_HOSTNAME/$ICR_NAMESPACE/$IMAGE_NAME:$${{ steps.prep.outputs.tags }}
          docker push $REGISTRY_HOSTNAME/$ICR_NAMESPACE/$IMAGE_NAME:latest   
